language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- pypy
- pypy3
install:
- pip install -r travis_requirements.txt
- python setup.py install
script: coverage run --source=datatables -m pytest -v
after_success: coveralls
